                html += "    <div class= 'form-group '>"
	        	html += "		<input type='hidden' name='seq' value=''>"
	        	html += "		<label>부모글의 정보(seq : )</label> <br>"
	        	html += "		<b>작성일 : </b>	        		"
	        	html += "	</div>"
	        	html += "	"
	        	html += "	<div class='form-group'>"
	        	html += "		<label>작성자</label>"
	        	html += "		<b>A003</b>"
	        	html += "	</div>"
	        	html += "	<div class='form-group'>"
	        	html += "		<label id='title'>제목(원본)</label>"
	        	html += "		<input class='form-control' name='title' id='title' value=''>"
	        	html += "	</div>"
	        	html += "	<div class='form-group'>"
	        	html += "		<label id='con'>내용(원본)</label>"
	        	html += "		<textarea class='form-control' rows='3' name='content' id='textValue' onclick='check()'></textarea>"
	        	html += "	</div>"
	        	html += "	<div class='modal-footer'>"
	        	html += "		<input type='button' class='btn btn-success' value='답글 작성' onclick='replyVal()'>"
	        	html += "		<span onclick='reset()'><input type='reset' class='btn btn-info' value='초기화'></span>"
	        	html += "		<button type='button' class='btn btn-default' data-dismiss='modal'>취소</button>"
	        	html += "	</div>"