SELECT SEQ , ID , TITLE , CONTENT , REGDATE , DELFLAG 
	FROM BOARD b ;

INSERT INTO BOARD
(SEQ, ID, TITLE, CONTENT, REGDATE, DELFLAG)
VALUES((SELECT MAX(SEQ)+1 FROM BOARD), '미키', '마웃스', '찾아요', SYSDATE , 'N');

UPDATE BOARD 
SET DELFLAG = 'Y';

